### ISSUE TITLE
store examples failing with `Cannot redefine property`

### ISSUE THREAD

**Issue by keturn** [kennyfrc/cami.js#10]
e.g. the cart example here https://jsfiddle.net/kennyfrc12/qjs8c2gb/15/

fails with
```
82:22: Uncaught TypeError: Cannot redefine property: cartItems
```

in current Chrome (123.0.6312.94)

**Comment by keturn** [comment]
I think I'm running in to two separate issues here:

1) The "Cannot redefine property" error comes from the fact that ReactiveElement.connect now calls `Object.defineProperty`, which means one should not attempt to define the property with normal field declaration syntax in the class body.

(I think it's also worth mentioning that the `key` used to retrieve the thing from the store is always used to define the name of the property on the Element.)

2) The store is somehow not updating? debug mode does send a `cami:state:change` message to the console with the correct newValue, but the `store.state` retains the old value.

**Comment by kennyfrc** [comment]
Hi @keturn! Thanks for calling this out.

My mistake on that one -- you essentially looked at outdated documentation (for some reason, I updated everything except the store docs).

I've updated the relevant sections in the site, and sharing the updated jsfiddle link below:

- JS Fiddle Link: [jsfiddle cart example](https://jsfiddle.net/kennyfrc12/qjs8c2gb/27)
- API: [store](https://camijs.com/api/observable_store/)

One thing that you may have noticed is that if you're familiar with other store implementations, it's now less like zustand and more similar to a mix of express/redux. I just found that in the production application that I'm working on, it's a lot more manageable with this new API.

In general, my folder structure looks like this:

```
elements/
  ├── elementName1
  ├── elementName2
  └── etc
index.js (this contains all the actions or .register calls)
store.js
```

I plan to write more about the architecture about non-trivial applications once I launch the production app that uses Cami (by June 2024)
